language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    # - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-27
    - android-24

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-24

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - cd QCloudCosXml
  - chmod a+x gradlew

script: ./gradlew connectedNormalAndroidTest